vaccines:
  - owid_name: "Covaxin"
    org_name: "Covaxin"
  - owid_name: "Johnson&Johnson"
    org_name: "J&J"
  - owid_name: "Moderna"
    org_name: "Moderna"
  - owid_name: "Oxford/AstraZeneca"
    org_name: "AstraZeneca"
  - owid_name: "Pfizer/BioNTech"
    org_name: "BioNTech"
  - owid_name: "Sinopharm/Beijing"
    org_name: "Sinopharm"
  - owid_name: "Sinovac"
    org_name: "Sinovac"
  - owid_name: "Sputnik V"
    org_name: "Sputnik V"

countries:
  - org_name: "Angola"
    owid_name: "Angola"
  - org_name: "Benin"
    owid_name: "Benin"
  - org_name: "Botswana"
    owid_name: "Botswana"
  - org_name: "Burkina Faso"
    owid_name: "Burkina Faso"
  - org_name: "Central African Republic"
    owid_name: "Central African Republic"
  - org_name: "Chad"
    owid_name: "Chad"
  - org_name: "Congo"
    owid_name: "Congo"
  - org_name: "Djibouti"
    owid_name: "Djibouti"
  - org_name: "Eswatini"
    owid_name: "Eswatini"
  - org_name: "Gabon"
    owid_name: "Gabon"
  - org_name: "Gambia"
    owid_name: "Gambia"
  - org_name: "Ghana"
    owid_name: "Ghana"
  - org_name: "Lesotho"
    owid_name: "Lesotho"
  - org_name: "Liberia"
    owid_name: "Liberia"
  - org_name: "Libya"
    owid_name: "Libya"
  - org_name: "Mali"
    owid_name: "Mali"
  - org_name: "Mauritania"
    owid_name: "Mauritania"
  - org_name: "Mauritius"
    owid_name: "Mauritius"
  - org_name: "Mozambique"
    owid_name: "Mozambique"
  - org_name: "Namibia"
    owid_name: "Namibia"
  - org_name: "Nigeria"
    owid_name: "Nigeria"
  - org_name: "Rwanda"
    owid_name: "Rwanda"
  - org_name: "Senegal"
    owid_name: "Senegal"
  - org_name: "Uganda"
    owid_name: "Uganda"
